### ISSUE TITLE
auto-install script to easily make a vps into a provider

### ISSUE THREAD

**Issue by NIXOYE** [leapcode/bitmask_client#1004]
It would be really helpful if their was an auto-install script that installed all dependencies etc. so people could easily become their own service provider with a vps\raspberry pi.

**Comment by micah** [comment]
Hi @NIXOYE !

There is actually something like this. Its called the LEAP Platform! https://leap.se/en/docs/platform

While it is tailored for Debian Jessie, we have not done any work to getting it to work on raspbian, so it may not work there.

**Comment by NIXOYE** [comment]
@micah 
i know of the tutorials i meant one script that installs it all for those who aren't technically inclined to be able to run a personal provider for their phones or laptops to use on wifi networks that aren't safe
