### ISSUE TITLE
connect to Tor before bitmask (User -> Tor -> bitmask -> Internet) broken

### ISSUE THREAD

**Issue by adrelanos** [leapcode/bitmask_client#1009]
Quotes from https://github.com/leapcode/bitmask_android/issues/147:

@meskio 

> Bitmask can't work right now on Tor. Up to now we are using udp for the VPN in bitmask, but tor only supports tcp. We are planning to add support for tcp, what will allow you to open a bitmask VPN on tor, but not sure when will be that.

@parmegv 

> hey! I just pushed the a beta version of Bitmask Android 0.9.0 to the Play Store and to dl.bitmask.net, and it tries TCP if UDP fails.

Using the desktop (linux) version of bitmask `0.9.2 (3a8198cd07)` this does not work. [I installed bitmask inside [Whonix](https://www.whonix.org)-Workstation.]

Is this to be expected? Can you fix that please?

**Comment by meskio** [comment]
We want to fix it but right now our focus is in email and VPN is in maintenance mode. Not sure when will a leap developer have time to fix this. But patches are welcome ;P

**Comment by meskio** [comment]
Migrated to our bugtracker: https://0xacab.org/leap/bitmask-dev/issues/9121
