### ISSUE TITLE
failure retrieving public key for debian stretch package

### ISSUE THREAD

**Issue by aguestuser** [leapcode/bitmask_client#1015]
Hi there! Trying to set up bitmask client on a fresh install of debian stretch (on GNU/Linux 4.8.0-2-amd64 with gpg v. 2.1.16) as per [these instructions](https://dl.bitmask.net/linux/#debian-testing-stretch).

When I run the second command to retrieve the public key for the package, I get the following output indicating an untrusted certificate:

```shell
root@mycomputer# wget -O- https://dl.bitmask.net/apt.key | apt-key add -
--2017-01-02 20:26:10--  https://dl.bitmask.net/apt.key
Resolving dl.bitmask.net (dl.bitmask.net)... 37.218.242.148
Connecting to dl.bitmask.net (dl.bitmask.net)|37.218.242.148|:443... connected.
ERROR: The certificate of ‘dl.bitmask.net’ is not trusted.
ERROR: The certificate of ‘dl.bitmask.net’ hasn't got a known issuer.
gpg: no valid OpenPGP data found.

```

When I try to run `apt update` i get this:

```shell
root@myomputer# apt update
<omited>
Err:4 http://deb.bitmask.net/debian testing InRelease                                           
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 1E34A1828E207901
<omited>
```

Is this because keys and/or certs are in the process of being updated? Is there further debugging I could do to verify its not a compatibility issue with my debian installation?

**Comment by micah** [comment]
Hi Austin,

Austin Guest <notifications@github.com> writes:

> Hi there! Trying to set up bitmask client on a fresh install of debian
> stretch (on GNU/Linux 4.8.0-2-amd64 with gpg v. 2.1.16) as per [these
> instructions](https://dl.bitmask.net/linux/#debian-testing-stretch).

If you are using stretch, you can just use the debian repository and do
`apt install leap-archive-keyring` because it is in Debian proper now.

> When I run the second command to retrieve the public key for the
> package, I get the following output indicating an untrusted
> certificate:
>
> ```shell
> root@mycomputer# wget -O- https://dl.bitmask.net/apt.key | apt-key add -
> --2017-01-02 20:26:10--  https://dl.bitmask.net/apt.key
> Resolving dl.bitmask.net (dl.bitmask.net)... 37.218.242.148
> Connecting to dl.bitmask.net (dl.bitmask.net)|37.218.242.148|:443... connected.
> ERROR: The certificate of ‘dl.bitmask.net’ is not trusted.
> ERROR: The certificate of ‘dl.bitmask.net’ hasn't got a known issuer.
> gpg: no valid OpenPGP data found.
>
> ```

Yeah, the cert was updated, but not the chain. I've fixed that now.

**Comment by aguestuser** [comment]
Hey Micah. Thanks! Worked like a charm!
