### ISSUE TITLE
Add support for deepin polkit agent

### ISSUE THREAD

**Issue by demonicpancake** [leapcode/bitmask_client#1026]
`# ps aux | grep polkit
polkitd    461  0.0  0.2 522852 17076 ?        Ssl  Jul10   0:00 /usr/lib/polkit-1/polkitd --no-debug
demonic+   752  0.0  0.3 646364 28592 ?        Sl   Jul10   0:03 /usr/lib/polkit-1-dde/dde-polkit-agent
`

:)

**Comment by meskio** [comment]
I've migrated it to our bugtracker: https://0xacab.org/leap/bitmask-dev/issues/9119

As we are about to close the issue submission in github.
