### ISSUE TITLE
Bitmask package problems (debian/jessie)

### ISSUE THREAD

**Issue by platschi** [leapcode/bitmask_client#897]
Failure encountered: Bitmask suddenly did not start some days ago. I remember updating debian packages. Now, it throws out a leap.common version conflict. No experimental installed previously, just the stable version from the repository. See Terminal output below.

System: 
Debian Release 8.2 (jessie), 
Kernel Linux 3.16.0-4-amd64
MATE 1.8.1

Installed <code>bitmask</code> and <code>leap-keyring</code> as by instructions on bitmask website. Worked previously, although already with some riseup certificate issues.

<code>/etc/apt/sources.list</code> as following (NB: /etc/apt/sources.list.d/ is empty): 
<pre>
deb http://http.us.debian.org/debian/ jessie main contrib
 deb http://security.debian.org/ jessie/updates contrib main
 
# wheezy-updates, previously known as 'volatile'
deb http://http.us.debian.org/debian/ jessie-updates contrib main
deb http://http.us.debian.org/debian/ jessie-proposed-updates main contrib
 
# bitmask
deb http://deb.bitmask.net/debian jessie main</pre>

Terminal throws out this (debian/jessie): 
<pre>
platschi@platschi:~$ bitmask
Traceback (most recent call last):
  File "/usr/bin/bitmask", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (leap.common 0.3.9 (/usr/lib/python2.7/dist-packages), Requirement.parse('leap.common>=0.4.0'))</pre>

On IRC, somebody mentioned to check <code>apt-cache policy bitmask</code>:

<pre>platschi@platschi:~$ apt-cache policy bitmask
bitmask:
  Installed: 0.8.1+0~20150228174625.131+jessie~1.gbpdd43da
  Candidate: 0.8.1+0~20150228174625.131+jessie~1.gbpdd43da
  Version table:
 *** 0.8.1+0~20150228174625.131+jessie~1.gbpdd43da 0
        500 http://deb.bitmask.net/debian/ jessie/main amd64 Packages
        100 /var/lib/dpkg/status</pre>

Help?!

**Comment by meskio** [comment]
This looks like a bug. `bitmask 0.8.1+0~20150228174625.131+jessie~1.gbpdd43da`, the one in the jessie repo, depends on python-leap-common (>= 0.3.7). The python-leap-common version in the jessie repo is `0.3.9+0~20141111213135.21+jessie~1.gbpd272a9`, what matches the package dependency, but somehow seems that bitmask requests >=0.4.0 to run. @kalikaneko should we package leap-common 0.4 for jessie? or could it be a mistake this run time check?

**Comment by platschi** [comment]
Got some new error message recently; maybe this helps fixing the issue finally? Would love using bitmask normally on debian jessie again :)

<pre>
platschi@platschi:~$ bitmask
/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py:203: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
  stacklevel=1,
Traceback (most recent call last):
  File "/usr/bin/bitmask", line 9, in <module>
    load_entry_point('leap.bitmask==0.8.1', 'console_scripts', 'bitmask')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/app.py", line 51, in <module>
    from leap.bitmask.frontend_app import run_frontend
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/frontend_app.py", line 30, in <module>
    from leap.bitmask.gui.mainwindow import MainWindow
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/gui/mainwindow.py", line 34, in <module>
    from leap.bitmask.backend.leapbackend import ERROR_KEY, PASSED_KEY
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend/leapbackend.py", line 25, in <module>
    from leap.bitmask.backend import components
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/backend/components.py", line 35, in <module>
    from leap.bitmask.config.providerconfig import ProviderConfig
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/config/providerconfig.py", line 27, in <module>
    from leap.bitmask.services import get_service_display_name
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/services/__init__.py", line 27, in <module>
    from leap.bitmask.crypto.srpauth import SRPAuth
  File "/usr/lib/python2.7/dist-packages/leap/bitmask/crypto/srpauth.py", line 40, in <module>
    from leap.common.events import signal as events_signal
ImportError: cannot import name signal
</pre>

**Comment by meskio** [comment]
This new error seems to be a similar problem. The version you have installed of leap.common is too old for the version of bitmask you are running.

Do you mind pasteing the output of the following command to see what versions you have of each package:
{{{
$ dpkg -l |egrep 'leap|bitmask|soledad'
}}}

We are about to release (maybe today) the 0.9.0, I hope the new packages will solve your problems.

**Comment by meskio** [comment]
It looks like we have updated the leap-common package before the rest of the packages, what has get bitmask broken :(

We are working on fixing it.

**Comment by platschi** [comment]
<pre>
platschi@platschi:~$ dpkg -l |egrep 'leap|bitmask|soledad'
ii  bitmask                               0.8.1+0~20150228174625.131+jessie~1.gbpdd43da     all          Provides the desktop client for the LEAP Encryption Access Project Platform.
ii  leap-keymanager                       0.3.8+0~20150512174853.31+jessie~1.gbp73e662      all          LEAP's Key Manager
ii  leap-keyring                          2015.02.26+0~20150226170049.17+sid~1.gbp30002f    all          GnuPG archive key of the leap.se repository
ii  leap-mail                             0.3.11.1~20150512162551.48+jessie                 all          Mail Services provided by Bitmask, the LEAP Client.
ii  python-leap-common                    0.4.11.1+0~20151102160657.36+jessie~1.gbpe074ea   all          Common Python files needed by LEAP projects
ii  soledad-client                        0.6.5.1+0~20150610191303.81+jessie~1.gbp48cecb    all          Synchronization of locally encrypted data among devices.
ii  soledad-common                        0.7.2+0~20150901200807.82+jessie~1.gbp363d96      all          Synchronization of locally encrypted data among devices (common files)
platschi@platschi:~$ 
</pre>

I'm on irc in case of any debugging needs :)

**Comment by platschi** [comment]
Problem solved after release of 0.9.1.  Happily Bitmasking again.

Good job, a 1000 thanks!
