### ISSUE TITLE
question: omit self-updates?

### ISSUE THREAD

**Issue by funkyfuture** [leapcode/bitmask_client#944]
as i'm hacking around in the downloaded package for generic Linux, changes will be overwritten during runtime by `leap.bitmask.updater`. is there a way to omit this behaviour?

**Comment by kalikaneko** [comment]
@funkyfuture it seems that you can nuke out the updates by moving launcher.conf out of its way

**Comment by funkyfuture** [comment]
since i'm trying it this way for more than a half day: the client keeps telling me that the backend (mail.bitmask.net) is not online; regardless the absence/presence of `launcher.conf`. is that to be expected atm or am i experiencing a client issue?

**Comment by funkyfuture** [comment]
a'ight, your proposal works. the connectability issue was caused by zmq still listening after a <ctrl + c> teardown.
