### ISSUE TITLE
[Request] Package for Ubuntu 14.10 Trusty

### ISSUE THREAD

**Issue by jcdenton2k** [leapcode/bitmask_client#960]
I'm running Linux Mint 17.3 based on Ubuntu 14.10 (Trusty)
So the bundle works fine, albeit with some hiccups.  Shortcuts will not work and I always have to run the application from the install directory.

This is a request from those of us who like using LTS releases to please strongly consider having a dedicated official BitMask package available for 14.10 Trusty again.  It used to be available in older versions and I don't understand what changed between then and now to cause package support for 14.10 to be dropped.

Also some code compilation instructions would be handy.  Not all of us are wizards (yet).

**Comment by micah** [comment]
Hi, 

Thanks for the report - we agree with you that removing Trusty packages was not great. We found it hard to maintain, and there were some security properties that we couldn't achieve there, so we decided to drop it. Even so, we hear your pain and we are looking at bringing it back soon!

**Comment by jcdenton2k** [comment]
@micah:
I appreciate the response, thanks so much for doing so!
What I'm not understanding is that the BUNDLE works fine in Trusty so why wouldn't a package work as well?  Would a package use different 'security properties'?

Please direct me towards the commits/discussions regarding this issue, or feel free to state them here.
I'm somewhat Linux-saavy so if there are some unmet dependencies preventing a package from being created then I'll try to get in touch with the Linux Mint folk and see what can be done.

I'm positive that when it comes to actual security enhancements, the Linux Mint folks may not be so hesitant to cling to outdated versions of software if it prevents stuff like BitMask from working properly.

I do want to say major kudos for at LEAST having a bundle working!  It is a kludge but it does work.
If I had some instructions for how to create a package from the bundle, I could start up an unofficial PPA (personal package archive) on ubuntu launchpad and do it that way.

Ideally though, the official BitMask devs should operate such a PPA if that is the best way to do it.

I'm still awaiting code compilation instructions for those of us who aren't automatic coding wizards (yet).  :)

**Comment by jcdenton2k** [comment]
Bringing this up again.

This page hasn't been updated in forever:
https://bitmask.net/en/install/linux

Ubuntu is on v16.04 (Xenial) now.  There hasn't been any updates on supporting either v14.04 LTS or v16.04 LTS.

Would like a status update if possible.

**Comment by elijh** [comment]
xenial LTS is supported. We were waiting for more testing, but I have updated the website with xenial instructions.

**Comment by jcdenton2k** [comment]
Thank ya for the update!
Still hoping for 14.04 LTS (Trusty) support; many Linux distros rely on it and haven't yet made the jump to 16.04 yet since it is still new-ish.
